import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

import ReduxProvider from "@/redux/ReduxProvider";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css";

const roboto = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BB Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} flex flex-col min-h-screen mx-3 md:mx-7 lg:w-[80%] lg:mx-auto text-slate-900 overflow-x-hidden bg-slate-100`}
      >
        <ReduxProvider>
          <ToastContainer limit={1} />
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
